abc_car/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings as django_settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('cars/', include('cars.urls', namespace='cars')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('socialaccounts/', include('allauth.urls')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
]

if django_settings.DEBUG:
    urlpatterns += static(django_settings.STATIC_URL, document_root=django_settings.STATIC_ROOT)
    urlpatterns += static(django_settings.MEDIA_URL, document_root=django_settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    path('', views.cars_list, name='list'),
    path('car/<slug:slug>/', views.car_detail, name='detail'),
    path('search/', views.search_func, name='search'),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('service/', views.service, name='service'),
]

templates/includes/footer.html
{% load static %}
<!-- Footer start -->
<footer class="footer">

    <div class="sub-footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <p class="copy">© {% now 'Y' %} Carzone Corp. All Rights Reserved.</p>
                </div>
                <div class="col-lg-4">
                    <div class="social-list-2">
                        <ul>
                            <li><a href="#" class="facebook-bg"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#" class="twitter-bg"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#" class="google-bg"><i class="fa fa-google-plus"></i></a></li>
                            <li><a href="#" class="linkedin-bg"><i class="fa fa-linkedin"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Footer end -->

templates/includes/messages.html
{% if messages %}
    {% for message in messages %}

        <div id="message" class="container">
            <div class="alert alert-{{ message.tags }}" alert-dismissable role="alert">
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
                <strong>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        ERROR:
                    {% else %}
                        {{ message.tags | title }}
                    {% endif %}
                </strong>
                {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}

templates/includes/navbar.html
{% load static %}
{% url 'pages:contact' as contact %}
{% url 'pages:service' as service %}
{% url 'pages:home' as home %}
{% url 'pages:about' as about %}
{% url 'cars:list' as cars %}

<!-- Main header start -->
<header class="main-header sticky-header header-with-top">
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="navbar-brand company-logo-2" href="{% url 'pages:home' %}">
                <img src="{% static 'img/logos/logo.png' %}" alt="logo">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar"
                    aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="fa fa-bars"></span>
            </button>
            <div class="navbar-collapse collapse w-100" id="navbar">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a
                                {% if home == request.path %}
                                    class="nav-link active"
                                {% else %}
                                    class="nav-link"
                                {% endif %}
                                    href="{{ home }}">
                            Home
                        </a>
                    </li>
                    <li class="nav-item">
                        <a  {% if cars == request.path or 'cars' in request.path %}
                            class="nav-link active"
                        {% else %}
                            class="nav-link"
                        {% endif %}
                            href="{{ cars }}">
                            Cars
                        </a>
                    </li>
                    <li class="nav-item">
                        <a  {% if about == request.path %}
                            class="nav-link active"
                        {% else %}
                            class="nav-link"
                        {% endif %}
                            href="{{ about }}">
                            About
                        </a>
                    </li>
                    <li class="nav-item">
                        <a  {% if service == request.path %}
                            class="nav-link active"
                        {% else %}
                            class="nav-link"
                        {% endif %}
                            href="{{ service }}">
                            Services
                        </a>
                    </li>


                    <li class="nav-item dropdown">
                        <a  {% if contact == request.path %}
                            class="nav-link active"
                        {% else %}
                            class="nav-link"
                        {% endif %}
                            href="{{ contact }}">
                            Contact</a>
                    </li>
                    <li class="nav-item dropdown m-hide">
                        <a href="#full-page-search" class="nav-link h-icon">
                            <i class="fa fa-search"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</header>
<!-- Full Page Search -->
<div id="full-page-search">
    <button type="button" class="close">×</button>
    <form action="{% url 'cars:search' %}" class="search-header">
        <input type="search" name="query"
               value="" placeholder="type keyword(s) here. Eg: audi, benz etc" aria-label/>
        <button type="submit" class="btn btn-sm button-theme">Search</button>
    </form>
</div>
<!-- Main header end -->

templates/includes/topbar.html
{% load static %}

<!-- Top header start -->
<header class="top-header th-2 top-header-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-7">
                <div class="list-inline">
                    <a href="tel:+55-4XX-634-7071"><i class="fa fa-phone"></i>+91-7013111501</a>
                    <a href="tel:info@themevessel.com"><i class="fa fa-envelope"></i>pinnampadmaraju@gmail.com</a>
                    <a href="tel:info@themevessel.com"><i class="fa fa-clock-o"></i>Mon - Sun: 8:00am - 6:00pm</a>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-5">
                <ul class="top-social-media pull-right">
                    {% if not request.user.is_authenticated %}
                        <li>
                            <a href="{% url 'accounts:login' %}"
                               class="sign-in"><i class="fa fa-sign-in"></i> Login</a>
                        </li>
                        <li>
                            <a href="{% url 'accounts:register' %}"
                               class="sign-in"><i class="fa fa-user"></i> Register</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'accounts:logout' %}"
                               class="sign-in"><i class="flaticon-logout"></i> Logout</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</header>
<!-- Top header end -->